### ISSUE TITLE
Refactor internal state structure to support better encapsulation and more efficient selectors

### ISSUE THREAD

**Issue by jrista** [briebug/ngrx-auto-entity#111]
The Auto-Entity library currently places all state "bare" on the state interface. As such, any time one of these properties changes, most of the selectors will re-fire, as they are being memoized based on this whole "root" entity state object.

```typescript
export interface IEntityState<TModel> {
  entities: IEntityDictionary<TModel>;
  ids: EntityIdentity[];
  currentEntityKey?: EntityIdentity;
  currentEntitiesKeys?: EntityIdentity[];
  editedEntity?: Partial<TModel>;
  isDirty?: boolean;
  currentPage?: Page;
  currentRange?: Range;
  totalPageableCount?: number;
  isLoading?: boolean;
  isSaving?: boolean;
  isDeleting?: boolean;
  loadedAt?: number;
  savedAt?: number;
  createdAt?: number;
  deletedAt?: number;
}
```

By moving all properties into one child object or another on the auto-entity state, it should allow more efficient and effective selectors, by "buffering" state changes and preventing selectors from emitting values when the relevant state has not actually changed. This would be due to input values for "child" selectors still pointing to previous references, and `defaultMemoize` should then return the previously computed, memoized value. 

```typescript
export interface IEntityState<TModel> {
  entities: IEntityDictionary<TModel>;
  ids: EntityIdentity[];
  selections: {
    currentEntityKey?: EntityIdentity;
    currentEntitiesKeys?: EntityIdentity[];
  };
  edits: {
    editedEntity?: Partial<TModel>;
    isDirty?: boolean;
  };
  paging: {
    currentPage?: Page;
    currentRange?: Range;
    totalPageableCount?: number;
  };
  tracking: {
    isLoading?: boolean;
    isSaving?: boolean;
    isDeleting?: boolean;
    loadedAt?: number;
    savedAt?: number;
    createdAt?: number;
    deletedAt?: number;
  };
}
```

Selectors such as these will emit values whenever the root entity state object changes, even if the specific properties these selectors handle have not changed:

```typescript
const selectCurrentEntity = createSelector(getState, mapToCurrentEntity);
const selectCurrentPage = createSelector(getState, mapToCurrentPage);
const selectIsLoading = createSelector(getState, mapToIsLoading);
const selectLoadedAt = createSelector(getState, mapToLoadedAt);
```

If "root property" selectors were created alongside a state structure change, such as these:

```typescript
const selectSelections = createSelector(getState, mapToSelections);
const selectPaging = createSelector(getState, mapToPaging);
const selectTracking = createSelector(getState, mapToTracking);
```

Even if the root state object has changed in one capacity or another, if only one of the root properties, say `tracking`, was actually modified:

```typescript
{...state, tracking: { ...state.tracking, isLoading: true } }
```

The `paging` and `selections` references would remain the same. The previous selectors could then be rewritten as:

```typescript
const selectCurrentEntity = createSelector(selectSelections, mapToCurrentEntity);
const selectCurrentPage = createSelector(selectPaging, mapToCurrentPage);
const selectIsLoading = createSelector(selectTracking, mapToIsLoading);
const selectLoadedAt = createSelector(selectTracking, mapToLoadedAt);
```

And actually benefit from the memoization provided by NgRx's `defaultMemoize` behavior. 

This change should be minimally breaking, assuming developers are using existing selectors or facade properties to select data from the auto-entity managed states. Even if developers are using selectors directly, and not just from the pre-fab facades, existing selector names and the data they return will not change. 

The only potentially breaking use case would be if developers have written their own selectors directly against auto-entity managed state. In this particular edge case, such selectors would need to be updated to handle the change in state structure. 

This change should have no impact on the inclusion of custom state with an entity state:

```typescript
const { initialState } = buildState(Customer, { myCustomState: 'hello' })
```

The above would continue to work.

**Comment by schuchard** [comment]
This sounds like a great idea.

**Comment by jrista** [comment]
Internal state structure was refactored in 0.8.0, along with updates to all selectors to utilize the new structure. A major overhaul of the reducer was implemented alongside the state structure changes, as much of the monolithic reducer had to be touched anyway to account for the structural changes. Testing so far indicates the changes are working as intended without any breaking issues or undue side effects.

**Comment by jrista** [comment]
Internal state structure was refactored in 0.8.0, along with updates to all selectors to utilize the new structure. A major overhaul of the reducer was implemented alongside the state structure changes, as much of the monolithic reducer had to be touched anyway to account for the structural changes. Testing so far indicates the changes are working as intended without any breaking issues or undue side effects.
