### ISSUE TITLE
Property 'entity' does not exist on type 'EntityAction<T>'

### ISSUE THREAD

**Issue by schuchard** [briebug/ngrx-auto-entity#116]
When responding to an entity success action, the `action` does not include the `entity` property on the type, causing a linter error. However, that value does exist on the action when the action is called.

```ts
this.actions$.pipe(
      ofEntityType(Entity, EntityActionTypes.CreateSuccess),
      map(action => action.entity // errors
```

using version: "~0.5.0-alpha.6"

**Comment by jrista** [comment]
Not all actions in Auto-Entity actually have an entity. Some, such as LoadAll, have no entity (there is no logical reason to have an entity or entities on such an action). The entity property exists on specific actions that derive from EntityAction<T>. 

There was limited typing available when Auto-Entity was first started, which at the time was during Angular 5/6 and I believe we were on TypeScript 2.x. It may be that today, with TypeScript 3.x, we can better type the `ofEntityType` operator and allow subsequent operators to know the concrete type of the action.

**Comment by jrista** [comment]
I believe, with the introduction of entity action factory functions similar to `createAction` from NgRx 8 and up, we will be able to solve the issues here. The fundamental issue is that `ofEntityType` actually returns `EntityAction`, the base action type of all other entity actions. That base class does not have an entity property.

With action factory functions, the type of every action would be strongly specified, and all the information appropriate for each action should be available in effects. I am not sure if there is a way to resolve the typing issues inherent to the `ofEntityType` operator...

**Comment by jrista** [comment]
Since we did in fact introduce the new entity-specific action creators, outside of legacy support, which hopefully will not be required going forward, I think this issue is no longer relevant. Closing for now.
