### ISSUE TITLE
Models with generic types end up `unkown`

### ISSUE THREAD

**Issue by schuchard** [briebug/ngrx-auto-entity#117]
when typing a model with a generic, the type inference is lost. Wondering if this can be supported. Sort of a super Entity use case here.

```ts
@Entity({ modelName: 'Alert' })
export class Alert<T = Record<string, any>> {
  @Key id?: string;
  entity?: T;
}
```

`buildState` appears unable to resolve the typing, thus resulting in the facade selectors (`entities`) returning an unknown type. The work around is to manually type it's usage.

```ts
buildState<IEntityState<unknown>, unknown, unknown, unknown>(type: IModelClass<unknown>, extraInitialState?: unknown): IModelState<unknown, IEntityState<unknown>, unknown, unknown>
```

**Comment by jrista** [comment]
Is this an entity that contains an entity?

**Comment by jrista** [comment]
Given the current typing, can the `Alert` entity be defined as so:

```typescript
@Entity({ modelName: 'Alert' })
export class Alert {
  @Key id?: string;
  entity?: Record<string, any>;
}
```

Since `T` is `Record<string, any>` I would think this would work. On the other hand, if `T` must derive from `Record<string, any>`, what happens if you type it like this:

```typescript
@Entity({ modelName: 'Alert' })
export class Alert<T extends Record<string, any>> {
  @Key id?: string;
  entity?: T;
}
```

**Comment by schuchard** [comment]
> Is this an entity that contains an entity?

No it's occasionally using an interface when I'd like to be more specific than just an "object".

> Since T is Record<string, any> I would think this would work. On the other hand, if T must derive from Record<string, any>, what happens if you type it like this:

```ts
@Entity({ modelName: 'Alert' })
export class Alert<T extends Record<string, any>> {
  @Key id?: string;
  entity?: T;
}
```

This leads to the same issue. `TModel` is `unknown` coming out of `buildState`

**Comment by jrista** [comment]
I've spent more time reviewing the options here, and I am not sure there is any way around the issue at the moment. We don't have any way to effectively track the use-case specific instances of a generic entity, unless each instance has its own state. If entity states were created for `Alert<Satellite>` and `Alert<Station>`, that would probably work, but state for the underlying generic itself, `Alert<T>`, is just not possible.
