### ISSUE TITLE
selectIds - unkown memoized type

### ISSUE THREAD

**Issue by schuchard** [briebug/ngrx-auto-entity#119]
the `selectIds` selector exposed by `buildState` has an unknown type in it's signature.

<img width="1138" alt="Screen Shot 2020-04-17 at 9 06 36 AM" src="https://user-images.githubusercontent.com/10186449/79584040-11765a80-808b-11ea-9817-426099cddc72.png">

**Comment by schuchard** [comment]
The issue arrives when using this selector among others. Typescript is unable to infer that it's a `string[]` and all consumers receive an `unknown` type.

**Comment by jrista** [comment]
The unknown type is the parent state. I think what we may have to do is adjust the order of the generic parameters for `buildState` and set them to some viable defaults initially (i.e. parent state could be `any`). I think the new order might need to be:

```typescript
export const buildState = <TParentState = any, TModel, TState extends IEntityState<TModel>, TExtra = any>(
  type: IModelClass<TModel>,
  extraInitialState?: TExtra
): IModelState<TParentState, TState, TModel, TExtra> =>
```

I'm not sure what we might default others to, but with this order we might be able to supply just the parent state type:

```typescript
const {initialState, selectors: {...}} = buildState<AppState>(Customer);
```

**Comment by jrista** [comment]
It may simply be that we must require the developer supply the `IParentState` regardless. Without supplying it, there is otherwise no way to infer it, as there is nothing passed into `buildState` that would give TS anything to work from in order to infer it.

**Comment by jrista** [comment]
I've extended the TParentState generic type from any in the `buildState`/`buildFeatureState` signatures. There is no way to know, by inference, what the type of the parent state will be at compile time short of requiring the developer manually specify every generic type these functions require. I figure `any` is better than `unknown`. This type is only really required internally, and it lacking a specific type does not have any notable impact on the usability/type safety of the selector map itself, or the types those selectors use/require from the end developer.
