### ISSUE TITLE
Error: Detected unserializable action at "info.modelType"

### ISSUE THREAD

**Issue by Inexad** [briebug/ngrx-auto-entity#159]
Hi,

I get error: Error: Detected unserializable action at "info.modelType".

**app.module.ts**

```
@NgModule({
    declarations: [
        AppComponent
    ],
    imports: [
        AppRoutingModule,
        BrowserModule,
        BrowserAnimationsModule,
        CommonModule,
        HttpClientModule,
        StateModule
    ],
    providers: [
        AuthService,
        { provide: Order, useClass: EntityService },
    ],
    bootstrap: [AppComponent],
})
export class AppModule {
}
```

**state.module.ts**
```
@NgModule({
    imports: [
        StoreModule.forRoot(appReducers,
            {
                runtimeChecks: {
                    strictStateImmutability: true,
                    strictActionImmutability: true,
                    strictStateSerializability: true,
                    strictActionSerializability: true,
                },
            }
        ),
        EffectsModule.forRoot([]),
        NgrxAutoEntityModule.forRoot()
    ]
})
export class StateModule { }
```

**app.state.ts**

```
export interface AppState {
    order: IEntityState<Order>;
}

export const appReducers: ActionReducerMap<AppState> = {
    order: orderReducer,
};
```
**order.model.ts**

```
@Entity({ modelName: 'Order' })
export class Order{
    @Key id?: string;
    name: string;

    constructor(obj?: any) {
        Object.assign(this, obj);
    }
}
```

If i change the runtimeChecks settings i get other errors instead, such as properties of order is readonly.

Any ideas what might be casing this? It worked fine before i updated to version: 0.5.0-alpha.7 from 0.4.1

I've been looking at similar problems: #45, #98 , but i can't see what i've done wrong. 

Regards.

**Comment by jrista** [comment]
This is normal with Auto-Entity. We are including the actual model class (a type) in the actions as the `.info` property. As such, Auto-Entity does not support strict action serializability. Because the model type is currently required in order to access all the key metadata added to each entity via the `@Entity` and `@Key` decorators, there is no way around this at the moment. 

You will simply need to disable strictActionSerializability to use Auto-Entity. We have not found this to be a problem in practice. Even with Redux Dev Tools, it has not been an issue.

**Comment by jrista** [comment]
Regarding the properties of order being readonly. This is also normal for NgRx in general. You should never modify an object you get out of state directly. That would be MUTATING an immutable object. This is the strict immutability checks saving you from yourself. ;) 

You also still have a non-default constructor. You cannot use non-default constructors with Auto-Entity. Your use of Object.assign() is inherently mutating in nature, and that is not allowed with the immutable nature of NgRx. This is an NgRx and general immutability thing, not really strictly an Auto-Entity thing.

Entities should only use the default constructor when using Auto-Entity, like so:

```typescript
@Entity('Order')
export class Order {
    @Key id?: string;
    name: string;
}
```

If you wish to make a strongly typed version of your Order, then you should be using the `makeEntity` function:

```typescript
export const {
	initialState: initialOrderState,
	makeEntity: makeOrder
} = buildState(Order);

const prototypedOrder = makeOrder({
	name: 'Test Order'
})
```

**Comment by Inexad** [comment]
Thanks ! I've disabled the strict serializeable settings.

In order to edit the object without mutating it, what is the best practise ? Currently i subscribe to current$ (or similiar) and edit it. This causes the read only property error. How would i get past this? Retrieve the object and store it in component before updating it?

Regards.

**Comment by jrista** [comment]
So, when you are editing. Is this normally through a form? Or are you modifying the entity data in other ways? My generally recommendation is to use Reactive Forms in Angular. I have a common pattern I use myself with container and presenter components that I'd be happy to share. It might be best to share that through the docs, though. Something I've been meaning to do on the gitbook docs is to add some "recipes" for various common patterns of use. I could start those off with how to edit entity data through a reactive form.

**Comment by Inexad** [comment]
Normally just throught different function calls in component when things happening. Can also be through forms. 

That sounds very useful!

**Comment by jrista** [comment]
I'll write something up as soon as I get a chance. The forms stuff is relatively simple in nature at a high level.

**Comment by Inexad** [comment]
The "Update"-function can't be used to update objects in this case i understand. It's only for the service call, i still need to build own reducer for updating the state before using the auto entity update function. Do i understand this correctly ?

**Comment by Inexad** [comment]
Above error got resolved after updating to latest auto-entity.

**Comment by jrista** [comment]
@Inexad I would avoid disabling `strictStateImmutability`. You are now mutating your state, which is a very bad thing. You should avoid that at all costs. 

To maintain immutability with NgRx in general, you need to COPY objects to modify them. You can no longer do:

```typescript
myEntity.someProperty = newValue;
```

Instead, you must now do this, which does a shallow clone of the original, and sets the new value of the property:

```typescript
const updatedMyEntity = {
  ...myEntity,
  someProperty: newValue
}
```

You would then save the updated copy:

```typescript
store.dispatch(new Update(MyEntity, updatedMyEntity));
```

**Comment by jrista** [comment]
If you want to make life a little easier on yourself when it comes to updating objects with strict immutability, you could look into ImmerJS. 

https://immerjs.github.io/immer/docs/introduction

**Comment by jrista** [comment]
@Inexad I forgot that I already had an example of a simple presenter form on our gitbook documentation. You can find it here:

https://briebug.gitbook.io/ngrx-auto-entity/examples/application/modal-component

```typescript
import { Component, Input, Output } from '@angular/core';
import { Customer } from '../models';

@Component({
  selector: 'app-customers-edit-form',
  templateUrl: './customers-edit-form.component.html',
  styleUrls: ['./customers-edit-form.component.scss']
})
export class CustomersEditFormComponent implements OnChanges, OnInit {
  @Input() customer: Customer;
  @Output() submitted = new EventEmitter<Customer>();
  @Output() validated = new EventEmitter<boolean>();
  
  form: FormGroup;
  
  constructor(private builder: FormBuilder) {}
  
  ngOnInit(): void {
    this.form = this.buildForm(this.builder);
    this.form.statusChanges.pipe(
      map(() => this.form.valid)
    ).subscribe(this.validated.emit);
  }
  
  ngOnChanges(): void {
    if (this.customer) {
      form.patchValue(customer);
    }
  }
  
  buildForm(builder: FormBuilder): FormGroup {
    return builder.group({
      name: [null, [Validators.required, Validators.maxLength(30)]],
      title: [null, [Validators.required, Validators.maxLength(60)]],
      email: [null, [Validators.required, Validators.maxLength(35)]],
      handles: builder.group({
        twitter: [null, Validators.maxLength(50)],
        facebook: [null, Validators.maxLenth(50)]
      }),
      address: builder.group({
        city: [null, Validators.maxLength(50)],
        state: [null, Validators.maxLength(2)],
        zip: [null, [Validators.minLength(5), Validators.maxLength(10)]]
      })
    });
  }
  
  submit() {
    if (this.form.invalid) {
      return;
    }
    
    const updatedCustomer = {
      ...this.customer,
      ...this.form.value
    };
    
    this.submitted.emit(updatedCustomer);
  }
}
```

In this case, submission of the form is externalized from the presenter to the parent container. However, it is just as easy to embed a submission button on the form presenter as well. In either case, you spread the original object, as you can see above in the `submit()` method, then spread the `form.value`. The reason I do this, is to ensure that any keys or other data on the original object that is NOT represented in the form, gets included in your updated entity object. By spreading the form.value second, you only override any properties from the original object that were included in the form. 

If necessary, you can then also manually set any properties, run calculations to set computed properties, etc. for any entity you edit in a form. This is an immutable-safe approach to editing data with forms in Angular.

**Comment by Inexad** [comment]
Hi,

@jrista Ok, so i need to copy object for every change. Got it. 

So i use below to do so:

```
const updatedMyEntity = {
  ...myEntity,
  someProperty: newValue
}

store.dispatch(new Update(MyEntity, updatedMyEntity));
```

When should i use the auto entity facade function: `Update()` ? I thought this function did the shallow copy and updated the state.

Thanks for the examples !

**Comment by jrista** [comment]
The pre-made facade can get you going with basic functionality. When you start moving into more advanced territory, you will usually find that you need to create some of your own actions, add new methods to the facade to dispatch those actions, and then write effects to handle those actions appropriately. When you get into effects, instead of using the facade, you would normally just create the actions you need when you need them (usually in an rxjs `map` in an effect). So, at that point, you would do something like `new Update(MyEntity, updatedMyEntity)`. (Note that in an effect, you don't use `store.dispatch`, as the effect itself will dispatch any effect that comes out of it. 

So, this reveals more content I need to add to our documentation on gitbook. ;) I've been a little behind on that side of things. I'm trying to get 0.6.x of Auto-Entity planned, which will normalize how actions work with NgRx 8+ (i.e. instead of `new Update(MyEntity, myEntity)`, you would do `updateMyEntity(myEntity)` instead). With this normalization, you'll be able to use auto-entity actions in NgRx 8+ reducers, with `ofType` etc. So that's diminished the time I've had to put towards our docs.

But I'm going to shift some of my priorities, and see if I can get more documentation written in our gitbook.

**Comment by Inexad** [comment]
@jrista Once again, thanks so much for throughout explanation !
