### ISSUE TITLE
Pagination - IEntityWithPageInfo

### ISSUE THREAD

**Issue by Inexad** [briebug/ngrx-auto-entity#165]
Hi,

Currently i use this code for retrieving page data (following documenation on Briebug): 
```
    loadPage(entityInfo: IEntityInfo, { page = 1, size = 25 }: Page): Observable<IEntityWithPageInfo<any>> {
        const skip: any = (page - 1) * size;
        const take: any = size;

        return this.http.get<any[]>(`${environment.rootUrl}/${entityInfo.modelName.camelToUnderscore()}`, { params: { skip, take } })
            .pipe(withLatestFrom(
                this.http.get<{ totalRecords: number; }>(`${environment.rootUrl}/${entityInfo.modelName.camelToUnderscore()}/count`, { params: { totalOnly: 'true' } })
            ),
                map(([data, total]) => ({
                    pageInfo: {
                        page: { page, size },
                        totalCount: total.totalRecords
                    },
                    entities: data
                }))
            );
    }
```
I can easily access current page and stuff from the facade. How can i access the `IEntityWithPageInfo` data ? I'm looking for the totalRecords value to show with my pagination. Is this possible to access without the need of creating own effects & actions for it ?

Regards.

**Comment by Inexad** [comment]
I now found what the problem was... 

`this.http.get<{ totalRecords: number; }>(....)` => I changed this to only type of number. Now i can access total results with: `totalPageable$`

**Comment by jrista** [comment]
@Inexad Aye. For the actual `get` generic type, you may need to specify exactly what you get back from the server, then use a .pipe() on the call to transform that, into what auto-entity expects. I need to improve our documentation on this on gitbook.
