### ISSUE TITLE
How do effects get triggered when using a Websocket instead of angular.common.http?

### ISSUE THREAD

**Issue by ri0t** [briebug/ngrx-auto-entity#167]
I've mostly adapted parts from the demo app to run with my websocket based backend and the most important bits do run. 

One important thing is lacking though: How do i enable triggering of the createSuccess/deleteSuccess effects for entities? 

Can you maybe give me an example of e.g. how to set up a entity-service delete-operation with a rxjs-websocket-based service? Thanks in advance!

**Comment by jrista** [comment]
Hi @ri0t. I'm sure we can figure out a solution. I'm curious if you have a demo project or source code somewhere that I could take a look at? 

One initial tip is that effects do not only have to work off of the Actions stream. Effects can operate off of any stream, so if your websocket has an Observable, you could write an effect to work from that stream initially, transform it to create the the necessary createSuccess/deleteSuccess actions, etc.

Auto-Entity also gives you direct control over which actions are handled by auto-entity itself. So, you could detatch the create action for specific entities, allowing you to handle them yourself, and use your websocket, if that is how you prefer to do things. I could show you how to do that as well.

Anyway, a glimpse at your code base would be a good start.

**Comment by jrista** [comment]
@ri0t Just wanted to check in and see if you were able to make the effects work for you as described. If not, I could still take a look at your current solution and see if I can offer more advice.
