### ISSUE TITLE
Multiple keys error

### ISSUE THREAD

**Issue by Inexad** [briebug/ngrx-auto-entity#203]
When defining entity like:

import { Entity, Key } from '@briebug/ngrx-auto-entity'

```
@Entity('ArticleSubGroup')
export class ArticleSubGroup {
  @Key id: number;
  @Key articleGroupId: string;
  externalId: number;
  name: string;
  active: boolean;
}
```

I get following error:

![image](https://user-images.githubusercontent.com/8613836/141480457-0607255c-10f5-4947-bfd4-c10e40c2e6fe.png)

I've followed example from documentation:

https://briebug.gitbook.io/ngrx-auto-entity/advanced/usage/building-your-entities

What i'm doing wrong ?

**Comment by jrista** [comment]
@Inexad Can you provide your environment details? Platform, angular version, auto-entity version, ngrx version? 

Maybe also specifically the typescript version as well... Multi-prop keys are definitely supported and we have used them ourselves, however...with NG12 typescript is in strict mode by default, and that might potentially be introducing new checks that we need to account for.

**Comment by Inexad** [comment]
Windows 10.

```
"dependencies": {
    "@angular-devkit/build-angular": "^12.2.13",
    "@angular/animations": "^12.1.4",
    "@angular/cdk": "^12.1.4",
    "@angular/common": "^12.1.4",
    "@angular/compiler": "^12.1.4",
    "@angular/core": "^12.1.4",
    "@angular/forms": "^12.1.4",
    "@angular/localize": "^12.1.4",
    "@angular/material": "^12.1.4",
    "@angular/platform-browser": "^12.1.4",
    "@angular/platform-browser-dynamic": "^12.1.4",
    "@angular/router": "^12.1.4",
    "@auth0/angular-jwt": "^5.0.2",
    "@briebug/ngrx-auto-entity": "^0.5.0",
    "@ngrx/effects": "^12.5.1",
    "@ngrx/store": "^12.5.1",
    "rxjs": "^6.5.3",
    "tslib": "^2.0.0",
    "zone.js": "~0.11.4"
  },
```

dev:
   "typescript": "~4.3.5"

**Comment by Inexad** [comment]
Sorry! I'm a retard.. In 0.6 of briebug it says this is fixed.

I close this.'
