### ISSUE TITLE
mongoDB

### ISSUE THREAD

**Issue by RBleyenberg** [briebug/ngrx-auto-entity#34]
Hodwy,

Question... normally within entity i do the following when monogdb is on the backend.

`export const adapter: EntityAdapter<Product> = createEntityAdapter<Product>({
  selectId: product => product._id
});`

Where do i do this the correct way within this awesome library.

Thanks in advanced.

**Comment by jrista** [comment]
Instead of using an adapter with an id selection function, we use a decorator called `@Key` that you decorate any key properties of your entity with. Our framework then utilizes that key property (or now, properties, as I recently implemented composite keys) as the id of the entity.

```javascript
export class MyEntity {
    @Key _id?: string; // MongoDB id property
    name: string;
    // ...
}
```
