### ISSUE TITLE
create action causing "update" is not a function error

### ISSUE THREAD

**Issue by richardshergold** [briebug/ngrx-auto-entity#47]
I was trying the create action on an entity collection (called Email) and I got the following error:

`NgRxAutoEntityService Error: Unable to invoke required operations on the EmailService Entity service "update" is not a function
`

I changed the action to a createMany and this seemed to work ok so I am wondering if there is a bug with the create action?

**Comment by jrista** [comment]
Thank you for the report, @richardshergold. Looks like I had a typo in one of our error messages. Will be fixed with the coming update to v0.2.

**Comment by jrista** [comment]
Resolved by #48
