### ISSUE TITLE
Gitbook Docs: consistency with repo example code, as well as some errors.

### ISSUE THREAD

**Issue by mxdmedia** [briebug/ngrx-auto-entity#57]
While working through setting up my first auto-entity project, I am finding some inconsistencies between the example code in the github repo and the examples in the gitbook docs, as well as a few errors.  Does the gitbook have a repo where PRs are accepted? I'd be happy to create some to help improve the docs.  In lieu of being able to submit PRs, I'll post what I am finding here.  So far I have found the following:

1. `From Scratch --> App Reducer`: missing `import { storeFreeze } from 'ngrx-store-freeze';`.
2. `From Scratch --> App Reducer`: reducer code (`appReducer` and `appMetaReducers`) is being placed in the file `app.state.ts`.  However in `From Scratch --> App State Module`, both `appReducer` and `appMetaReducers` are being imported from `app.reducer.ts`.
3. From 2, importing from `app.reducer.ts` is inconsistent with the github example code, which puts everything in `app.state.ts`.
4. `From Scratch --> App State Module`: missing `import { NgrxAutoEntityModule } from '@briebug/ngrx-auto-entity';`
5. `From Scratch --> App State Module`: missing comma after `StoreModule.forRoot(appReducer, { metaReducers: appMetaReducers })`
6. `From Scratch --> Entity State`: Indicates that `customers.state.ts` should be located at `src/app/state/state/customer.state.ts`, whereas the example code has the entity state files located at `src/app/state/<entity>.state.ts`
7. `From Scratch --> Entity State`: Customer model import path is: `models/customer.model`, which would be `src/app/state/state/models` whereas in the example code, models live in `<root>/src/app/models`.
8. `From Scratch --> Update App State`: More import consistency issues.  `Customer` is being imported from `models` which would be in `src/app/state/models`, and `customerReducer` is imported from `./customer.state.ts` which is consistent with the github code, but not what is mentioned on the `From Scratch --> Entity State` gitbook page.
9. `From Scratch --> Update App Module`: Similar consistency issue for `Customer` import.  Appears to be coming from `<root>/src/app/models` rather than from `<root>/src/app/state/models`.  Also, there is a typo: `{ provide: Custmer, useClass: EntityService }` should be `{ provide: Customer, useClass: EntityService }`.

Other than these consistency issues (which are easily fixable, but might be somewhat confusing to someone who is relatively new to ngrx and/or angular) the docs were great, and got me up and running very efficiently.  I hope this is helpful, and since I'll be diving deep into the docs over the next few days, I'm happy to provide more feedback, or even PRs if the gitbook is in an accessible repo somewhere.

**Comment by jrista** [comment]
Doc issues mentioned above have been corrected. Documentation may now be updated by forking the new docs repo and PRing changes in that way, if future docs issues are found:

https://github.com/briebug/ngrx-auto-entity-docs
