### ISSUE TITLE
Feature Request- Auto date conversion via decorator.

### ISSUE THREAD

**Issue by mxdmedia** [briebug/ngrx-auto-entity#59]
I'm not sure if this would be within the scope you envision for auto-entity, but along the "auto" lines...

One common (at least for me) operation I regularly apply to my store data is converting back and forth from strings to dates.  In particular, within my app, I typically want a javascript `Date` object, but obviously my API sends and expects formatted datetime strings.  So, would it make sense to add a decorator to the model interface, that specifies that a parameter is a Date/Datetime, and its string representation?  e.g.:

```typescript
export Appointmentl {
  @Key id: number;
  name: string;
  description: string;
  @Date('YYYY-MM-DDTHH:mm:ssZ') datetime: Date;
}
```

The parameter in the `@Date` decorator specifies the incoming/outgoing string format.  It would then auto-convert incoming dates to a javascript `Date` object, and auto-convert the `Date` object to the proper string format the remote API expects.  Then in all of your selectors you get back a native `Date` object.

**Comment by jrista** [comment]
So, this might be something I could work into another decorator I am working on, `@Entity`. The entity decorator will allow you to "configure" each entity model. Now, date conversion is something you could handle already in the entity service, but I'll think about options for adding it to the entity decorator in the future.

With the entity service, converting dates would be pretty strait forward:

```typescript
public load(entityInfo: IEntityInfo, id: number) {
    return this.http.get(...).pipe(map(entity => ({
        ...entity,
       date: new Date(entity.date)
    })));
}

public update(entityInfo: IEntityInfo, entity: Entity) {
    return this.http.put(..., {...entity, date: entity.toISOString()});
}

// ... etc. ...
```

Now, granted, this is not something you necessarily want to do repeatedly, and eliminating repetitive things is what Auto-Entity is all about, so I'll definitely be looking into this for you. You CAN reuse entity services, if you have an API that would support it. You might need to get clever, but it should be possible even to define your own decorators to track date format conversions and the like, and dynamically handle mapping in a single rich shared entity service. 

Until I am able to release another version of the library, hopefully handling your date mapping (or any other mapping for that matter) through the entity services will tide you over.

To pave the way for how I think I'll probably need to implement this, so you can prepare for it, my guess is I'll probably take an approach like the following:

```typescript
import { Entity, Key, DESCENDING } from '@briebug/ngrx-auto-entity';

// If your dates come from the DB as an ISO8601 string...
export function EntityDateStringConverter(sourceDate: string) {
    return Date.parse(sourceDate);
}

// If your dates are stored as an ng-bootstrap NgbDateStruct 
export function EntityDateObjectConverter(sourceDate: NgbDateStruct) {
    return new Date(sourceDate.year, sourceDate.month-1, sourceDate.day);
}

// To parse with Luxon
export function EntityDateLuxonConverter(sourceDate: string) {
    return DateTime.fromISO(sourceDate);
}

// etc.

export function CustomerSortComparer(a: Customer, b: Customer) {
    return a.name.localeCompare(b.name, null, {numeric: true});
}

@Entity({
   pluralName: 'Customersss', // Custom plural name
   dateConverter: EntityDateStringConverter,
   sortComparer: CustomerSortComparer,
   excludeEffects: matching(EntityActionTypes.Load) // Only allow bulk loads
})
export class Customer {
    @Key id: number;
    @SortKey(DESCENDING) name: string;
    @Date dateRegistered: Date;
}
```

My hope is you will be able to specify a dateConverter for the model (and this could be imported from elsewhere in your code if you need to share it). For now, this would need to be specified on each model, however I am going to try to support global config as well, so you would eventually be able to specify a default converter in the .forRoot() and/or .forFeature() methods when importing the module. 

There are other things coming with the @Entity decorator. Aside from dynamic plurality naming, which should make creating entity services a little easier, there will also be the ability to manually specify a plural name. I am also adding functionality to allow you to configure which entity effects are applied for which actions on a per-model basis. 

This will effectively allow you to exclude certain entities from being automatically handled by Auto-Entity if for some reason you must handle certain actions yourself (i.e. you could still dispatch Load(Customer, 1), but you would have to write your own effect to handle that action and dispatch the appropriate LoadSuccess/LoadFailure actions in response to whatever you do.)

I am also working on the default sort order functionality, and as you can see that will also integrate with the `@Entity` decorator in a manner similar to date conversion. You will not be required to create your own sortComparer function. By default, I will use an internal sort comparer that will try to perform the necessary comparison based on the `@SortKey` decorated properties, using the sort direction defined (or ascending as default). 

If for some reason the default sort does not work properly (the default sorter will do what it can, but with various different potential property types, I am going to have to limit how complex I allow the default sort comparer to be, so there will undoubtedly be edge cases I cannot handle properly without making the whole feature much too complex.) As with date converters, I would allow the default sort comparer to be replaced with global config as well.

**Comment by mxdmedia** [comment]
Fantastic!  The entity service will work great for my current use case, and looks quite easy to implement.  Thanks for the sample code.

I really like your thoughts on a possible future implementation.  I think it would make doing formatting like this easier and be very flexible.  In my case, I use the `date-fns` library throughout my code to handle date calculations, so the flexibility to use its formatting/parsing functions would be great (and clearly I can use `date-fns` to do the conversions in the entity service).

Another useful decorator (that can currently be implemented in the entity service now that I think about it) is "read-only".  I have an api used in an old app that is very rigid.  For example, each instance of a data model had a `created` and `updated` datetime stamp, which were read-only.  And rather than just not updating them if you provided a new value, the API would return an invalid parameter error, and perform no update/create.  So the ability to easily mark parameters as read-only, and suppress them from updates/create/etc.. would be useful as well.

**Comment by jrista** [comment]
@mxdmedia I wonder if you could leverage TypeScript features to support your readonly needs. If you want to prevent users from changing a property on an object, I think that may be out of the scope of Auto-Entity. I am not sure how I would enforce that. 

TypeScript, however, should be able to enforce that at compile time, if it has the features. You might also be able to write a decorator to enforce it at runtime.... There is also the linter option as well. A TSLint/ESLint rule might be able to be written to enforce readonly or immutability for specific properties (maybe decorated by a custom decorator.) 

Might be a little tricky, since you would need to be able to assign the properties at least once, during creation of the object. Not sure how you would handle that one exception.

**Comment by mxdmedia** [comment]
The more I have worked with Auto-entity, the more I realize the read-only bit really isn't needed.  

Rather than a true "read only" where auto-entity/typescript would enforce that the user cant change the value in Javascript, I was implying that a parameter specified as ReadOnly would automatically be suppressed from being passed back to the API on write operations (as I have this one API endpoint that throws an error if you pass back, say the "created" date).  But this can easily be accomplished in my entity services, and is an edge case, so its really not too big a deal.

**Comment by jrista** [comment]
Yup! Sounds like you are getting a handle on things. I've been busy ramping up another project lately, but I hope to get back to the Entity decorator and all those useful features soon.

**Comment by jrista** [comment]
I think I am going to take a more general approach to type conversion, though. Instead of having an explicit date converter, I am heading more in a direction where you can define any number of converters, name them, and then apply them to properties of your models with something like:

```typescript
import { Entity, Key, DESCENDING } from '@briebug/ngrx-auto-entity';

// If your dates come from the DB as an ISO8601 string...
export function EntityDateStringConverter(sourceDate: string) {
    return Date.parse(sourceDate);
}

export function CustomerSortComparer(a: Customer, b: Customer) {
    return a.name.localeCompare(b.name, null, {numeric: true});
}

@Entity({
   pluralName: 'Customersss', // Custom plural name
   typeConverters: [
       { name: 'date', useFunction: EntityDateStringConverter }
   ],
   sortComparer: CustomerSortComparer,
   excludeEffects: matching(EntityActionTypes.Load) // Only allow bulk loads
})
export class Customer {
    @Key id: number;
    @SortKey(DESCENDING) name: string;
    @Converter('date') dateRegistered: Date;
}
```

Converters will also hopefully be configurable at the module level, by passing in configuration to `.forRoot()` or `.forFeature()`.

**Comment by jrista** [comment]
@mxdmedia I've been looking into ways to solve the transformation problem. I think we are going to go with a much simpler, but vastly more flexible approach. Instead of defining type converters, we are simply going to allow the developer to define transformation functions, for `fromServer` and `toServer` paths. These transforms would be applied by auto-entity between when the developer's entity services are called, and the data gets back into NgRx, effects and state. 

The approach is actually pretty simple, and gives the developer total control over all transformations. It simply adds a transformations property to the entity decorator, which takes two transformation functions, `fromServer` and `toServer` both of which are optional:

```typescript
export interface IEntityTransformer {
  fromServer?: <TModel>(entity: any) => TModel;
  toServer?: <TModel>(entity: TModel) => any;
}

export interface IEntityOptions {
  modelName: string;
  uriName?: string;
  pluralName?: string;
  comparer?: (a, b) => number;
  transform?: IEntityTransformer;
  excludeEffects?: IEffectExclusions | IEffectExcept;
}
```

This will allow very different data to be loaded from the server, then transformed into the entities you use in your app, as well as taking the entities you use in the app and transform them into very different forms when being sent to the server.
