### ISSUE TITLE
Typos in doc

### ISSUE THREAD

**Issue by Edouardbozon** [briebug/ngrx-auto-entity#61]
Hi, 

I spotted some typos in documentation and I read in #57 that for now you're using Github issues to fix things in documentation. In my opinion it could be a waste of time and very fastidious. 

Gitbook provides the ability to [connect documentation to a repository](https://docs.gitbook.com/integrations/github). It can help us to contribute more directly. 

What do you think ?

**Comment by jrista** [comment]
Hi @Edouardbozon, and thank you for the tip. I'll look into connecting the gitbook docs to a repo this weekend so you guys can start fixing typos. I appreciate the support there. I'll post here once I have that working.

**Comment by jrista** [comment]
Documentation can now be updated by forking:

https://github.com/briebug/ngrx-auto-entity-docs
