### ISSUE TITLE
Fix: Entity performance

### ISSUE THREAD

**Issue by schuchard** [briebug/ngrx-auto-entity#94]
Dealing with a large quantity of entities (7k or more) is considerably slower than `@ngrx/entity` (16.5 sec vs 800ms) when loading into state. Perhaps a less immutable approach would improve performance.

**Comment by jrista** [comment]
We definitely do not have the most optimally performant code for reduction at the moment. I used a very immutable approach, but it sounds like we could use some optimization to handle larger data sets. I think that should be fairly strait forward, though, so I'll prioritize getting refactoring the reducer. A general refactoring was something I already had on my plate, as we'll need to break down the current meta reducer anyway to support some of the alternative ways of using the library (i.e. a move towards more NgRx 8 style factory functions for the actions, as an alternative (but not replacement for) newing up the current EntityAction objects). 

I can tackle optimizing the reduction along with refactoring the reducers.
